# Generated by Django 4.1.7 on 2023-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_poster_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='content',
            field=models.TextField(max_length=100, verbose_name='content'),
        ),
    ]
