# Generated by Django 3.2.16 on 2023-03-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_poster_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='url'),
        ),
    ]
