# Generated by Django 3.2.16 on 2023-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230312_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='content',
            field=models.TextField(max_length=160, verbose_name='content'),
        ),
    ]
