# Generated by Django 3.2.16 on 2023-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_poster_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
